# Generated by Django 5.2.5 on 2025-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVShows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
