# Generated by Django 5.2.5 on 2025-09-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo_ninjas_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ninja",
            old_name="title",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="ninja",
            name="last_name",
            field=models.CharField(default="unknonw", max_length=255),
            preserve_default=False,
        ),
    ]
