# Generated by Django 5.2.5 on 2025-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo_ninjas_app", "0002_rename_title_ninja_first_name_ninja_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dojo",
            name="desc",
            field=models.TextField(default="old dojo"),
        ),
    ]
