# Generated by Django 5.2.5 on 2025-09-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_app', '0002_remove_message_user_book_delete_comment_and_more'),
        ('user_login_app', '0002_remove_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='title',
            new_name='species',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='users_who_like',
        ),
        migrations.AddField(
            model_name='tree',
            name='date_found',
            field=models.DateField(default="2025-09-15"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tree',
            name='location',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tree',
            name='notes',
            field=models.TextField(default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tree',
            name='users_who_visit',
            field=models.ManyToManyField(related_name='visited_trees', to='user_login_app.user'),
        ),
        migrations.AddField(
            model_name='tree',
            name='zip_codes',
            field=models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='tree_app.zipcode'),
            preserve_default=False,
        ),
    ]
